jobs:
- job: Packages

  steps:
  - checkout: self
    clean: true

  - task: GitVersion@3
    inputs:
      updateAssemblyInfo: false

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.9.1
      checkLatest: false

  - task: NuGetCommand@2
    inputs:
      command: restore
      solution: Controls/UWPControls.sln
      selectOrConfig: select
      includeNuGetOrg: true
      verbosityRestore: Normal

  - task: MSBuild@1
    inputs:
      solution: Controls/UWPControls.sln
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /p:Configuration=Release "/p:Platform=Any CPU" /detailedsummary "/p:PackageVersion=$(GITVERSION.FullSemVer)" "/p:InformationalVersion=$(GITVERSION.InformationalVersion)" "/p:PackageOutputPath=$(build.artifactstagingdirectory)"
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Build.SourcesDirectory)\SDKExamples.iOS\bin
      Contents: '**\*.ipa'
      TargetFolder: $(build.artifactstagingdirectory)\ios

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Build.SourcesDirectory)\SDKExamples.Droid\bin
      Contents: '**\*.apk'
      TargetFolder: $(build.artifactstagingdirectory)\android

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Build.SourcesDirectory)\SDKExamples.Wasm\bin\Release\netstandard2.0\dist
      Contents: '**\*.*'
      TargetFolder: $(build.artifactstagingdirectory)\android

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: TelerikUWP-drop
      ArtifactType: Container